harry_potter_facts2 = [
    "The first Harry Potter book was published in 1997.",
    "J.K. Rowling came up with the idea for Harry Potter while on a delayed train from Manchester to London in 1990.",
    "Harry Potter's birthday is July 31st, which is also J.K. Rowling's birthday.",
    "The Hogwarts motto is 'Draco Dormiens Nunquam Titillandus,' which means 'Never tickle a sleeping dragon.'",
    "Hogwarts is located in Scotland.",
    "The Hogwarts Express departs from Platform 9 3/4 at King’s Cross Station.",
    "The four Hogwarts houses are Gryffindor, Hufflepuff, Ravenclaw, and Slytherin.",
    "The Sorting Hat originally belonged to Godric Gryffindor.",
    "Dumbledore's full name is Albus Percival Wulfric Brian Dumbledore.",
    "Harry Potter’s wand is 11 inches long and made of holly with a phoenix feather core.",
    "Voldemort’s real name is Tom Marvolo Riddle.",
    "Hermione Granger’s middle name is Jean.",
    "The Weasley family’s home is called The Burrow.",
    "The spell 'Expelliarmus' is known as the disarming charm.",
    "The Deathly Hallows consist of the Elder Wand, the Resurrection Stone, and the Invisibility Cloak.",
    "Quidditch was invented by J.K. Rowling while she was stuck in a small apartment.",
    "The Golden Snitch was originally called the Golden Snidget, which was a live bird used in early Quidditch games.",
    "The name 'Hogwarts' was inspired by a plant J.K. Rowling saw in a botanical garden.",
    "Harry's patronus is a stag.",
    "Hermione's patronus is an otter.",
    "Ron's patronus is a Jack Russell Terrier.",
    "Dobby is a free elf.",
    "The Malfoy family lives in Malfoy Manor.",
    "Severus Snape loved Lily Potter.",
    "The Room of Requirement only appears to those who need it most.",
    "Bellatrix Lestrange is Sirius Black’s cousin.",
    "The Dark Mark is a skull with a snake coming out of its mouth.",
    "Hagrid’s first name is Rubeus.",
    "Hagrid’s pet dragon was named Norbert, later revealed to be a female Norwegian Ridgeback named Norberta.",
    "Fred and George Weasley’s joke shop is called Weasleys' Wizard Wheezes.",
    "The Marauder’s Map was created by Moony, Wormtail, Padfoot, and Prongs.",
    "James Potter’s nickname was Prongs.",
    "Luna Lovegood’s father runs The Quibbler magazine.",
    "The Triwizard Tournament involves three tasks.",
    "Cedric Diggory represented Hogwarts in the Triwizard Tournament.",
    "Harry Potter speaks Parseltongue, the language of snakes.",
    "Gringotts Wizarding Bank is run by goblins.",
    "The Knight Bus is a triple-decker bus for stranded witches and wizards.",
    "Harry’s vault number at Gringotts is 687.",
    "The first Horcrux destroyed was Tom Riddle’s diary.",
    "The basilisk in the Chamber of Secrets was killed by Harry with Godric Gryffindor’s sword.",
    "The Weasley clock shows the location of each family member.",
    "Harry’s middle name is James.",
    "Ginny Weasley’s real first name is Ginevra.",
    "Remus Lupin is a werewolf.",
    "Tonks’ full name is Nymphadora Tonks.",
    "The Elder Wand is the most powerful wand in existence.",
    "Fawkes is Dumbledore’s phoenix.",
    "The Whomping Willow was planted to protect the entrance to the Shrieking Shack.",
    "The Pensieve is a device used to view memories.",
    "The Killing Curse is 'Avada Kedavra.'",
    "The Lovegood home is shaped like a rook from a chess set.",
    "The Deluminator was created by Dumbledore.",
    "The Fidelius Charm is used to hide secret locations.",
    "Sirius Black’s Animagus form is a dog.",
    "The Black family home is located at 12 Grimmauld Place.",
    "Crookshanks is part Kneazle.",
    "Neville Longbottom’s parents were tortured by Bellatrix Lestrange.",
    "The Mirror of Erised shows a person’s deepest desire.",
    "The Sword of Gryffindor was made by goblins.",
    "Nagini is Voldemort’s snake and one of his Horcruxes.",
    "The Hogwarts library contains a restricted section.",
    "The Polyjuice Potion allows someone to temporarily take on the appearance of another person.",
    "The Patronus Charm is 'Expecto Patronum.'",
    "Sybill Trelawney is the Divination professor at Hogwarts.",
    "Mad-Eye Moody’s real name is Alastor Moody.",
    "The Yule Ball is a traditional part of the Triwizard Tournament.",
    "Harry inherited the Invisibility Cloak from his father, James Potter.",
    "Dolores Umbridge’s patronus is a cat.",
    "Hedwig was Harry’s snowy owl.",
    "Hermione’s cat, Crookshanks, is orange and fluffy.",
    "The first Dumbledore’s Army meeting was held in the Room of Requirement.",
    "Voldemort is often referred to as 'He Who Must Not Be Named.'",
    "The Black family tree is embroidered on a tapestry.",
    "The spell 'Lumos' creates light.",
    "The spell 'Nox' extinguishes light.",
    "J.K. Rowling first came up with the idea for Harry Potter while traveling by train from Manchester to London in 1990.",
    "The series consists of seven books: Harry Potter and the Philosopher's Stone, Harry Potter and the Chamber of Secrets, Harry Potter and the Prisoner of Azkaban, Harry Potter and the Goblet of Fire, Harry Potter and the Order of the Phoenix, Harry Potter and the Half-Blood Prince, and Harry Potter and the Deathly Hallows.",
    "The book series was translated into over 80 languages, including Latin and Ancient Greek.",
    "The series has sold over 500 million copies worldwide, making it one of the best-selling book series in history.",
    "Harry Potter was initially rejected by 12 publishers before it was accepted by Bloomsbury.",
    "The first book, Philosopher's Stone, was originally titled Harry Potter and the School of Magic in Rowling's early drafts.",
    "The name 'Harry Potter' was inspired by a boy who used to live near Rowling’s childhood home.",
    "Hogwarts castle was inspired by a combination of real places, including the Edinburgh Castle and other Scottish landmarks.",
    "J.K. Rowling came up with the idea for Hogwarts’ houses after a visit to a boarding school where students were divided into houses.",
    "The symbol for Gryffindor is a lion, and its colors are red and gold.",
    "The symbol for Hufflepuff is a badger, and its colors are yellow and black.",
    "The symbol for Ravenclaw is an eagle, and its colors are blue and silver (or blue and bronze in the books).",
    "The symbol for Slytherin is a serpent, and its colors are green and silver.",
    "Hogwarts has four houses: Gryffindor, Hufflepuff, Ravenclaw, and Slytherin.",
    "The Sorting Hat, which sorts students into their houses, is enchanted to choose the house that best suits the student’s personality.",
    "Harry’s iconic lightning bolt scar is on his forehead, and it is the result of Voldemort's failed attempt to kill him when he was a baby.",
    "Harry’s parents, Lily and James Potter, were murdered by Lord Voldemort when Harry was just an infant.",
    "Harry Potter’s middle name is James, after his father.",
    "Hermione Granger was inspired by Rowling’s own experiences in school, where she was known as a bright and determined student.",
    "Ron Weasley comes from a large family; he has five brothers and one sister.",
    "The Weasley family is known for their red hair, freckles, and big personalities.",
    "The Weasley twins, Fred and George, are known for their prank shop, Weasleys' Wizard Wheezes.",
    "The Invisible Cloak is one of the three Deathly Hallows and is a family heirloom passed down to Harry.",
    "Harry’s pet owl, Hedwig, is a snowy owl and plays a vital role in delivering letters and messages.",
    "The mirror of Erised shows the deepest desires of a person’s heart. Harry sees his parents in the mirror.",
    "The first book was published in 1997, and the last one, Deathly Hallows, came out in 2007.",
    "The Harry Potter films are based on the books and are among the highest-grossing film franchises in history.",
    "Daniel Radcliffe played Harry Potter in the film adaptations.",
    "Emma Watson portrayed Hermione Granger, and Rupert Grint played Ron Weasley in the films.",
    "Voldemort's real name is Tom Marvolo Riddle.",
    "The dark mark is a symbol used by Lord Voldemort and his Death Eaters, often associated with terror and death.",
    "Dobby is a house-elf who becomes one of Harry’s allies.",
    "The Philosopher’s Stone grants immortality through the Elixir of Life.",
    "The Triwizard Tournament is a magical competition featured in Harry Potter and the Goblet of Fire.",
    "Hogwarts' headmaster during Harry’s time was Albus Dumbledore.",
    "Severus Snape was the Potions Master and later became the Defense Against the Dark Arts professor.",
    "The Half-Blood Prince refers to Snape's childhood alias.",
    "The Deathly Hallows are three powerful magical objects: the Elder Wand, the Resurrection Stone, and the Invisibility Cloak.",
    "The Elder Wand is the most powerful wand in existence and is considered unbeatable.",
    "The Resurrection Stone has the ability to bring back the dead, but they are not truly alive.",
    "The Invisibility Cloak makes the wearer completely invisible.",
    "The Marauders were James Potter, Sirius Black, Remus Lupin, and Peter Pettigrew, who created the Marauder's Map.",
    "The Marauder's Map is a magical map that shows the entire layout of Hogwarts and the movements of everyone within it.",
    "Hogwarts students have to take a series of magical exams called the O.W.L.s (Ordinary Wizarding Levels) and N.E.W.T.s (Nastily Exhausting Wizarding Tests).",
    "Hermione Granger's parents are Muggles (non-magical people), and she is a Muggle-born witch.",
    "The house-elf tradition of servitude is controversial in the wizarding world, as seen with characters like Dobby and Winky.",
    "The first book in the series was published by Bloomsbury in the UK and Scholastic in the USA.",
    "The UK version of the first book was called *Philosopher's Stone*, while in the US, it was called *Sorcerer's Stone*.",
    "The magical creatures featured in the series include Hippogriffs, Thestrals, Centaurs, and Blast-Ended Skrewts.",
    "The invisibility cloak was passed down to Harry by his father, James Potter.",
    "Lord Voldemort's Horcruxes are objects in which a dark wizard can store pieces of their soul to achieve immortality.",
    "Harry first learns of the wizarding world when he receives his Hogwarts letter on his 11th birthday.",
    "The Dark Mark is used to summon Voldemort's Death Eaters and marks the scene of their terror.",
    "The Room of Requirement is a magical room in Hogwarts that appears only when a person truly needs it.",
    "Fawkes, the phoenix, is Albus Dumbledore's companion and a symbol of rebirth.",
    "Hagrid is the Keeper of Keys and Grounds at Hogwarts, as well as a half-giant.",
    "The Knight Bus is a magical transport system used by wizards when in need of urgent travel.",
    "Harry's first broomstick is a Nimbus 2000, which is later replaced by a Firebolt in the third book.",
    "Voldemort is often described as having a very pale and snake-like appearance.",
    "The Weasley family’s magical home is called The Burrow.",
    "The Ministry of Magic is the governing body of the magical community in Britain.",
    "The Death Eaters are followers of Voldemort who use dark magic to carry out his bidding.",
    "Luna Lovegood is known for her quirky personality and unique perspectives.",
    "Bellatrix Lestrange is a loyal follower of Voldemort and is known for her insanity and cruelty.",
    "Harry’s Patronus is a stag, like his father’s.",
    "Hermione's Patronus is an otter, which symbolizes her playful and intelligent nature.",
    "Ron’s Patronus is a Jack Russell Terrier, reflecting his loyalty and bravery.",
    "Professor Minerva McGonagall is a transfiguration teacher at Hogwarts and the head of Gryffindor House.",
    "The Triwizard Cup is a magical artifact used in the Triwizard Tournament.",
    "The prophecy about Harry and Voldemort states that neither can live while the other survives.",
    "The Peverell brothers created the Deathly Hallows according to wizarding legend.",
    "Harry's first significant victory over Voldemort comes in *Chamber of Secrets* when he destroys the basilisk.",
    "The Quidditch World Cup plays a major role in *The Goblet of Fire*.",
    "The Pensieve is a magical object that allows one to view and even enter memories.",
    "Horace Slughorn is the Potions Master at Hogwarts in *Half-Blood Prince*.",
    "Voldemort uses Nagini, a giant snake, as one of his Horcruxes and as his loyal companion.",
    "The Deathly Hallows are a central theme in *The Deathly Hallows*, the final book of the series.",
    "Fred Weasley tragically dies during the Battle of Hogwarts.",
    "The Elder Wand's true master is Harry Potter, who wins it from Draco Malfoy in a duel.",
    "The Ravenclaw common room is located in a tower and requires a riddle to be answered for entry.",
    "The Slytherin common room is located under the lake, with windows offering a view of the water.",
    "The Gryffindor common room is located in a tower and is accessed through a portrait of the Fat Lady.",
    "The Hufflepuff common room is located near the kitchens and is accessible by a stack of large barrels.",
    "The Weasley twins' joke shop, Weasleys' Wizard Wheezes, is a popular establishment in Diagon Alley.",
    "The magic of Apparition allows wizards to teleport from one location to another instantly.",
    "Harry's lightning scar is a key symbol throughout the series, representing his connection to Voldemort.",
    "Hogwarts students are required to take Defense Against the Dark Arts, Potions, and Transfiguration as part of their core subjects.",
    "Professor Flitwick is the Charms teacher at Hogwarts and the head of Ravenclaw House.",
    "Gilderoy Lockhart is a famous wizard who becomes the Defense Against the Dark Arts teacher in *Chamber of Secrets*. He is known for his obsession with fame and self-promotion.",
    "The Weasley family is often portrayed as one of the most loving and supportive families in the series.",
    "Dumbledore's Army is a secret student group formed by Harry, Hermione, and Ron to teach fellow students how to defend themselves against dark magic.",
    "Draco Malfoy is a prominent antagonist throughout the series, often opposing Harry and his friends.",
    "The Deathly Hallows were originally introduced in *The Tales of Beedle the Bard*, a book of wizarding fairy tales.",
    "Harry's scar burns when Voldemort is near or when Voldemort is feeling a strong emotion like anger or rage.",
    "Tom Riddle created his first Horcrux using the diary of Tom Riddle, which played a major role in *The Chamber of Secrets*.",
    "The Basilisk in *Chamber of Secrets* is a giant snake whose gaze can petrify or kill anyone who looks directly into its eyes.",
    "Harry’s first broomstick, the Nimbus 2000, was a gift from Professor McGonagall when he joined the Gryffindor Quidditch team.",
    "The Patronus Charm is one of the most difficult spells to master and is used to protect oneself from Dementors.",
    "The Weasley twins invent several magical products, including Skiving Snackboxes, which cause the consumer to experience different symptoms to avoid schoolwork.",
    "The Half-Blood Prince's book is filled with helpful potion-making instructions and dark magical notes, which Harry uses to excel in Potions class.",
    "Professor Umbridge, introduced in *The Order of the Phoenix*, becomes one of the most disliked characters due to her cruelty and her strict, oppressive rule over Hogwarts.",
    "The Horcruxes are pieces of Voldemort's soul, and he splits his soul into these objects to avoid death and gain immortality.",
    "Harry and his friends are able to destroy Voldemort's Horcruxes with various magical methods, including the use of basilisk venom and the Sword of Gryffindor.",
    "Hogwarts houses have their own unique ghost: Nearly Headless Nick (Gryffindor), the Fat Friar (Hufflepuff), the Grey Lady (Ravenclaw), and the Bloody Baron (Slytherin).",
    "The wizarding world has its own currency: Galleons, Sickles, and Knuts.",
    "The Forbidden Forest is located on the outskirts of Hogwarts and is filled with dangerous and magical creatures.",
    "The Triwizard Tournament was a magical competition that took place once every five years and was originally meant to be a friendly event between three wizarding schools: Hogwarts, Beauxbatons, and Durmstrang.",
    "The magical map known as the Marauder's Map is able to show the entire Hogwarts castle, including secret passages and the whereabouts of every person within the school.",
    "The first instance of Quidditch in the series happens during Harry's first year at Hogwarts, when he joins the Gryffindor team as the youngest Seeker in a century.",
    "The Room of Requirement is a magical room that appears when a person is in desperate need of it. It can transform into nearly anything the person requires.",
    "Fawkes, Dumbledore’s phoenix, has the ability to regenerate by bursting into flames and being reborn from its ashes.",
    "Harry first learns he is a wizard when Hagrid comes to deliver his Hogwarts acceptance letter and explains the wizarding world to him.",
    "The Mirror of Erised shows the deepest desires of a person’s heart, but it does not allow the person to interact with their desire. It only reflects it.",
    "Voldemort's obsession with pure-blood wizarding heritage is reflected in his treatment of Muggle-borns, like Hermione Granger, whom he calls 'Mudblood'.",
    "The Dark Lord uses Nagini, a giant serpent, to do his bidding, and she also becomes one of Voldemort’s Horcruxes.",
    "Ron’s pet rat, Scabbers, is eventually revealed to be an animagus named Peter Pettigrew, who faked his own death to betray Harry's parents.",
    "The prophecy about Harry and Voldemort, which was made before Harry’s birth, foretold that only one could live while the other survived.",
    "The Deathly Hallows are important in *The Deathly Hallows* because they can be used to defeat Voldemort. The Elder Wand is key to winning over Voldemort’s power.",
    "Harry’s wand is made of holly wood and has a phoenix feather core. It shares a connection with Voldemort’s wand, as both contain feathers from the same phoenix, Fawkes.",
    "The magical world contains a wide variety of dangerous creatures, including Dementors, whom Harry faces on multiple occasions.",
    "In *The Prisoner of Azkaban*, Harry learns that Sirius Black is his godfather and that he was falsely accused of betraying his parents.",
    "Sirius Black is a member of the Marauders and is known for his Animagus form as a large black dog.",
    "The *Order of the Phoenix* is a secret group founded by Dumbledore to fight against Voldemort’s return and to protect the wizarding world.",
    "The Half-Blood Prince's identity is revealed to be Severus Snape, who has a complicated history with Harry and his parents.",
    "The magic spell 'Expelliarmus', used frequently by Harry, is a disarming charm that causes the opponent to lose their weapon or item.",
    "The magical species known as house-elves, like Dobby and Kreacher, possess powerful magic but are bound by tradition and servitude.",
    "Gilderoy Lockhart, an incompetent wizard who seeks fame, is revealed to be a fraud after he accidentally erases his own memory.",
    "In the final battle in *The Deathly Hallows*, Harry faces Voldemort in a duel at Hogwarts, leading to the Dark Lord’s ultimate defeat.",
    "The Patronus Charm is used to protect against Dementors. Harry is able to cast a full-bodied Patronus in his third year at Hogwarts.",
    "The Weasley family has a lot of children, and they are known for their warmth, generosity, and loyalty.",
    "Neville Longbottom is initially portrayed as clumsy but later plays a key role in defeating Voldemort by destroying the final Horcrux, Nagini.",
    "Hermione Granger, though extremely intelligent and resourceful, also struggles with self-doubt, especially in her younger years.",
    "The Weasley family is considered a blood traitor family because they openly welcome Muggle-borns and oppose Voldemort’s blood purity ideals.",
    "Voldemort’s real name, Tom Riddle, is a reference to his attempts to hide his Muggle heritage and create a new identity.",
    "The Weasley twins invent several joke products, including Extendable Ears and Peruvian Instant Darkness Powder.",
    "In *Harry Potter and the Goblet of Fire*, Harry competes in the Triwizard Tournament after his name is mysteriously chosen by the Goblet of Fire.",
    "The magical world’s use of owls to send letters and messages is one of the iconic features of the series.",
    "Fawkes, the phoenix, can heal people with his tears, as seen when he saves Harry’s life during the encounter with the basilisk in *Chamber of Secrets*.",
    "In *The Prisoner of Azkaban*, Harry first learns how to use the Time-Turner to travel back in time to save Sirius Black and Buckbeak.",
    "The Order of the Phoenix includes key figures such as Sirius Black, Remus Lupin, and Mad-Eye Moody, all of whom fight to protect Harry and defeat Voldemort.",
    "The wizarding world has numerous magical creatures, including Hippogriffs, Acromantulas (giant spiders), and Thestrals (flying horses).",
    "Harry’s connection to Voldemort is strengthened when Voldemort unintentionally makes Harry one of his Horcruxes.",
    "The key theme throughout the series is the battle between good and evil, symbolized by Harry’s fight against Voldemort and his followers, the Death Eaters.",
    "The magical creature called Buckbeak is a Hippogriff that plays a major role in *The Prisoner of Azkaban*.",
    "In *Harry Potter and the Half-Blood Prince*, Dumbledore is tragically killed by Severus Snape, marking a pivotal moment in the series."
]

harry_potter_facts = [
    "The first Harry Potter book was published in 1997.",
    "J.K. Rowling came up with the idea for Harry Potter while on a delayed train from Manchester to London in 1990.",
    "Harry Potter's birthday is July 31st, which is also J.K. Rowling's birthday.",
    "The Hogwarts motto is 'Draco Dormiens Nunquam Titillandus,' which means 'Never tickle a sleeping dragon.'",
    "Hogwarts is located in Scotland.",
    "The Hogwarts Express departs from Platform 9 3/4 at King’s Cross Station.",
    "The four Hogwarts houses are Gryffindor, Hufflepuff, Ravenclaw, and Slytherin.",
    "The Sorting Hat originally belonged to Godric Gryffindor.",
    "Dumbledore's full name is Albus Percival Wulfric Brian Dumbledore.",
    "Harry Potter’s wand is 11 inches long and made of holly with a phoenix feather core.",
    "Voldemort’s real name is Tom Marvolo Riddle.",
    "Hermione Granger’s middle name is Jean.",
    "The Weasley family’s home is called The Burrow.",
    "The spell 'Expelliarmus' is known as the disarming charm.",
    "The Deathly Hallows consist of the Elder Wand, the Resurrection Stone, and the Invisibility Cloak.",
    "Quidditch was invented by J.K. Rowling while she was stuck in a small apartment.",
    "The Golden Snitch was originally called the Golden Snidget, which was a live bird used in early Quidditch games.",
    "The name 'Hogwarts' was inspired by a plant J.K. Rowling saw in a botanical garden.",
    "Harry's patronus is a stag.",
    "Hermione's patronus is an otter.",
    "Ron's patronus is a Jack Russell Terrier.",
    "Dobby is a free elf.",
    "The Malfoy family lives in Malfoy Manor.",
    "Severus Snape loved Lily Potter.",
    "The Room of Requirement only appears to those who need it most.",
    "Bellatrix Lestrange is Sirius Black’s cousin.",
    "The Dark Mark is a skull with a snake coming out of its mouth.",
    "Hagrid’s first name is Rubeus.",
    "Hagrid’s pet dragon was named Norbert, later revealed to be a female Norwegian Ridgeback named Norberta.",
    "Fred and George Weasley’s joke shop is called Weasleys' Wizard Wheezes.",
    "The Marauder’s Map was created by Moony, Wormtail, Padfoot, and Prongs.",
    "James Potter’s nickname was Prongs.",
    "Luna Lovegood’s father runs The Quibbler magazine.",
    "The Triwizard Tournament involves three tasks.",
    "Cedric Diggory represented Hogwarts in the Triwizard Tournament.",
    "Harry Potter speaks Parseltongue, the language of snakes.",
    "Gringotts Wizarding Bank is run by goblins.",
    "The Knight Bus is a triple-decker bus for stranded witches and wizards.",
    "Harry’s vault number at Gringotts is 687.",
    "The first Horcrux destroyed was Tom Riddle’s diary.",
    "The basilisk in the Chamber of Secrets was killed by Harry with Godric Gryffindor’s sword.",
    "The Weasley clock shows the location of each family member.",
    "Harry’s middle name is James.",
    "Ginny Weasley’s real first name is Ginevra.",
    "Remus Lupin is a werewolf.",
    "Tonks’ full name is Nymphadora Tonks.",
    "The Elder Wand is the most powerful wand in existence.",
    "Fawkes is Dumbledore’s phoenix.",
    "The Whomping Willow was planted to protect the entrance to the Shrieking Shack.",
    "The Pensieve is a device used to view memories.",
    "The Killing Curse is 'Avada Kedavra.'",
    "The Lovegood home is shaped like a rook from a chess set.",
    "The Deluminator was created by Dumbledore.",
    "The Fidelius Charm is used to hide secret locations.",
    "Sirius Black’s Animagus form is a dog.",
    "The Black family home is located at 12 Grimmauld Place.",
    "Crookshanks is part Kneazle.",
    "Neville Longbottom’s parents were tortured by Bellatrix Lestrange.",
    "The Mirror of Erised shows a person’s deepest desire.",
    "The Sword of Gryffindor was made by goblins.",
    "Nagini is Voldemort’s snake and one of his Horcruxes.",
    "The Hogwarts library contains a restricted section.",
    "The Polyjuice Potion allows someone to temporarily take on the appearance of another person.",
    "The Patronus Charm is 'Expecto Patronum.'",
    "Sybill Trelawney is the Divination professor at Hogwarts."
]
